serverConfig:
  node.environment: test
  http-server.http.port: 8083

routingRules:
  rulesEngineEnabled: False
  # rulesConfigPath: "src/main/resources/rules/routing_rules.yml"

dataStore:
  jdbcUrl: jdbc:postgresql://192.168.80.241:5432/trinogateway
  user: trinogateway
  password: trinogateway
  driver: org.postgresql.Driver
  queryHistoryHoursRetention: 24

clusterStatsConfiguration:
  monitorType: INFO_API

# This can be adjusted based on the coordinator state
monitor:
  taskDelaySeconds: 10

modules:
  - io.trino.gateway.ha.module.HaGatewayProviderModule
  - io.trino.gateway.ha.module.ClusterStateListenerModule
  - io.trino.gateway.ha.module.ClusterStatsMonitorModule

managedApps:
  - io.trino.gateway.ha.clustermonitor.ActiveClusterMonitor
